/* ============================================================
   COLONIAL INDIA // CITY INTEL DATABASE
   Each record: name, alias, lat, lng, tier, classification,
   image, known_for, colonial_history
   ============================================================ */

const WIKI = (file, w) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${w||640}`;

/* ---------- TIER 1 — MAJOR COLONIAL CITIES ---------- */
const TIER1 = [
  {
    name: "Calcutta", alias: "Kolkata", lat: 22.5726, lng: 88.3639,
    classification: "PRESIDENCY CAPITAL",
    image: WIKI("Victoria_Memorial_situated_in_Kolkata.jpg"),
    known_for: "The cultural capital of eastern India, famed for its literary and artistic 'Bengal Renaissance', grand colonial architecture, and the Howrah Bridge over the Hooghly. A city of intellectuals, trams, and Durga Puja.",
    colonial_history: "Founded as a fortified trading post by Job Charnock of the East India Company in 1690, Calcutta grew around Fort William. The 1756 'Black Hole of Calcutta' and Robert Clive's victory at Plassey (1757) made it the springboard of British dominion in Bengal. It served as the capital of British India from 1772 until 1911, when the seat moved to Delhi. As the Company and later Crown headquarters, it was the nerve centre of trade, opium revenue, and administration."
  },
  {
    name: "Bombay", alias: "Mumbai", lat: 18.9388, lng: 72.8354,
    classification: "PRESIDENCY CAPITAL",
    image: WIKI("Chhatrapati_Shivaji_Terminus,_Mumbai.jpg"),
    known_for: "India's commercial and financial powerhouse, home to the Gateway of India, Victorian Gothic and Art Deco ensembles, and the heart of the Hindi film industry. A teeming archipelago city built on reclaimed land.",
    colonial_history: "The seven islands passed from Portugal to the English Crown in 1661 as part of Catherine of Braganza's dowry, then were leased to the East India Company in 1668. Bombay became the capital of the Bombay Presidency and the chief western port, booming on cotton during the American Civil War. Its docks, mills, and railway terminus (Victoria Terminus, 1887) made it the gateway of imperial commerce and a crucible of the nationalist movement."
  },
  {
    name: "Madras", alias: "Chennai", lat: 13.0827, lng: 80.2707,
    classification: "PRESIDENCY CAPITAL",
    image: WIKI("Chennai_Central.jpg"),
    known_for: "The cultural heart of South India, known for Carnatic music, Marina Beach, Dravidian temples, and a long maritime tradition. The cradle of British settlement on the subcontinent.",
    colonial_history: "Fort St. George, founded in 1639 on a coastal strip granted to Francis Day of the East India Company, was the first English fortress in India and the seed of Madras. It became the capital of the Madras Presidency, governing most of South India. The city was briefly captured by the French under La Bourdonnais in 1746 before being restored, and grew into a major military, administrative, and educational centre of the Raj."
  },
  {
    name: "Delhi", alias: "Dilli", lat: 28.6139, lng: 77.2090,
    classification: "IMPERIAL CAPITAL",
    image: WIKI("Red_Fort_in_Delhi_03-2016_img3.jpg"),
    known_for: "The seat of empires across a thousand years, layered with Mughal monuments — the Red Fort, Jama Masjid, Humayun's Tomb — and the planned grandeur of Lutyens' New Delhi.",
    colonial_history: "Delhi was the symbolic heart of Mughal power and the epicentre of the 1857 Rebellion, when sepoys proclaimed the aged Bahadur Shah Zafar emperor before the British besieged and brutally recaptured the city. In 1911 King George V announced at the Delhi Durbar that the capital would shift from Calcutta; Edwin Lutyens and Herbert Baker then designed New Delhi, inaugurated in 1931 as the monumental capital of the Raj."
  },
  {
    name: "Lahore", alias: "", lat: 31.5204, lng: 74.3587,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Badshahi_Mosque_in_Lahore.jpg"),
    known_for: "The cultural capital of Punjab, celebrated for Mughal splendour — the Badshahi Mosque, Shalimar Gardens, and Lahore Fort — and a rich tradition of poetry and learning.",
    colonial_history: "Capital of Ranjit Singh's Sikh Empire until its fall, Lahore was annexed by the British after the Second Anglo-Sikh War in 1849. It became the capital of the British province of Punjab, a major garrison and railway hub. The city hosted Government College and the University of the Punjab and, in 1940, the Muslim League's 'Lahore Resolution' calling for a separate Muslim state — a milestone on the road to Partition."
  },
  {
    name: "Karachi", alias: "", lat: 24.8607, lng: 67.0011,
    classification: "PORT CITY",
    image: WIKI("Frere_Hall_Karachi.jpg"),
    known_for: "A sprawling Arabian Sea port, gateway to the Indus, known for its colonial-era civic buildings and its later role as Pakistan's first capital and largest metropolis.",
    colonial_history: "A small fishing settlement under the Talpur rulers of Sind, Karachi was captured by Sir Charles Napier in 1843, who reputedly signalled the conquest with the pun 'Peccavi' ('I have sinned'). The British developed it into a deep-water port to export Punjab's wheat and cotton, building the harbour, cantonment, and railway. It grew rapidly as the principal seaport of north-western India."
  },
  {
    name: "Rangoon", alias: "Yangon", lat: 16.8409, lng: 96.1735,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Shwedagon-Pagoda-Night.jpg"),
    known_for: "The golden-spired capital of Burma, dominated by the Shwedagon Pagoda, a city of broad colonial boulevards, teak, and the rice trade of the Irrawaddy delta.",
    colonial_history: "Rangoon was annexed after the Second Anglo-Burmese War in 1852 and made the capital of British Burma, administered as a province of British India until 1937. The British laid out a grid-plan city, developed the port, and made it the world's leading rice-exporting harbour. The last Mughal emperor, Bahadur Shah Zafar, was exiled and died here in 1862, while the deposed Burmese king Thibaw was sent the opposite way to India."
  },
  {
    name: "Dacca", alias: "Dhaka", lat: 23.8103, lng: 90.4125,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Ahsan_Manzil_Pink_Palace_Dhaka_Bangladesh_(1).jpg"),
    known_for: "The historic centre of Bengal's muslin trade, riverine and densely woven, capital of present-day Bangladesh and home to the rose-coloured Ahsan Manzil.",
    colonial_history: "Once a Mughal provincial capital famed for fine muslin, Dacca declined as British policy and Manchester's mills destroyed its weaving industry. It served briefly as capital of the new province of Eastern Bengal and Assam after Lord Curzon's controversial 1905 Partition of Bengal, a move reversed in 1911 amid fierce nationalist protest. The University of Dacca was founded in 1921 partly in recompense."
  },
  {
    name: "Hyderabad", alias: "", lat: 17.3850, lng: 78.4867,
    classification: "PRINCELY STATE",
    image: WIKI("Charminar_Hyderabad_1.jpg"),
    known_for: "City of the Charminar and Golconda Fort, famed for pearls, biryani, and the syncretic Deccani culture of the Nizams — once among the richest men on earth.",
    colonial_history: "Hyderabad was the largest and wealthiest princely state, ruled by the Nizams who allied early with the British and signed a subsidiary alliance in 1798. Though never formally annexed, the state was bound by treaty, hosting a British Resident and the Secunderabad cantonment. The Nizam retained nominal sovereignty until 1948, when the independent Indian army's 'Operation Polo' forcibly integrated the state into India."
  },
  {
    name: "Bangalore", alias: "Bengaluru", lat: 12.9716, lng: 77.5946,
    classification: "GARRISON TOWN",
    image: WIKI("Bangalore_Vidhana_Soudha.jpg"),
    known_for: "The 'Garden City' of pleasant climate, parks, and lakes — later India's technology capital, but historically a cantonment town and seat of Mysore's administration.",
    colonial_history: "Bangalore was a fortress of Hyder Ali and Tipu Sultan, stormed by Lord Cornwallis in 1791 during the Third Anglo-Mysore War. After Tipu's defeat at Seringapatam in 1799, the British established a large cantonment here in 1809, governed directly as an 'Assigned Tract' while the old city remained under the Mysore maharaja. The mild climate made it a favoured European station with a substantial military presence."
  },
  {
    name: "Lucknow", alias: "", lat: 26.8467, lng: 80.9462,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Bara_Imambara_Lucknow.jpg"),
    known_for: "Capital of the Nawabs of Awadh, byword for refined Urdu, courtly etiquette ('pehle aap'), kebabs, and the elaborate Bara Imambara.",
    colonial_history: "The wealthy kingdom of Awadh was annexed by Lord Dalhousie in 1856 on the pretext of misgovernment, an act that inflamed sepoy resentment. In 1857 Lucknow became a centre of the Rebellion, and the British Residency endured a famous five-month siege. The relief and recapture of Lucknow were among the bloodiest episodes of the uprising; the shell-scarred Residency was preserved as an imperial memorial."
  },
  {
    name: "Allahabad", alias: "Prayagraj", lat: 25.4358, lng: 81.8463,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Allahabad_-_Triveni_Sangam.jpg"),
    known_for: "Sacred confluence (Sangam) of the Ganga, Yamuna, and mythical Saraswati, host to the vast Kumbh Mela, and a centre of law, learning, and politics.",
    colonial_history: "Allahabad's great Mughal fort commanded the rivers, and it was here in 1858 that Queen Victoria's Proclamation transferring India from Company to Crown rule was read aloud. The city became the capital of the United Provinces and seat of a High Court. It was a crucible of nationalism — home to the Nehru family's Anand Bhavan and the venue of key Indian National Congress sessions."
  },
  {
    name: "Patna", alias: "", lat: 25.5941, lng: 85.1376,
    classification: "PROVINCIAL CAPITAL",
    image: WIKI("Golghar_Patna.jpg"),
    known_for: "Ancient Pataliputra, capital of the Maurya and Gupta empires, strung along the Ganga; known for the beehive-shaped Golghar granary and Sikh shrine Takht Sri Patna Sahib.",
    colonial_history: "Patna was a key East India Company centre for the opium and saltpetre trade. The 1763 'Patna Massacre' of English prisoners by Mir Qasim's forces helped trigger the decisive Battle of Buxar (1764), which secured Company control of Bengal, Bihar, and Orissa. The British built the giant Golghar granary in 1786 after a devastating famine, and Patna became capital of the new Bihar and Orissa province in 1912."
  },
  {
    name: "Kanpur", alias: "Cawnpore", lat: 26.4499, lng: 80.3319,
    classification: "GARRISON TOWN",
    image: WIKI("All_Souls_Memorial_Church_Kanpur.jpg"),
    known_for: "An industrial city on the Ganga, the 'Manchester of the North' for its leather and textile mills, with a heavy military and manufacturing legacy.",
    colonial_history: "As Cawnpore, the city held a major British garrison and was the site of the most notorious episode of 1857: Nana Sahib's forces besieged the European garrison, and the killings at Satichaura Ghat and the Bibighar massacre became a rallying cry for vengeful British reprisals. After the Rebellion, Cawnpore developed into a leading industrial centre with army-supplying leather and woollen factories."
  },
  {
    name: "Amritsar", alias: "", lat: 31.6340, lng: 74.8723,
    classification: "TRADING POST",
    image: WIKI("Golden_Temple,_Amritsar.jpg"),
    known_for: "Spiritual capital of Sikhism, home to the Golden Temple (Harmandir Sahib), a great commercial and pilgrimage city of Punjab.",
    colonial_history: "Founded by the Sikh Guru Ram Das, Amritsar flourished under Maharaja Ranjit Singh before British annexation in 1849. It is forever marked by the Jallianwala Bagh massacre of 13 April 1919, when General Reginald Dyer ordered troops to fire on an unarmed crowd in an enclosed garden, killing hundreds. The atrocity galvanised the independence movement and shattered moderate faith in British justice."
  },
  {
    name: "Surat", alias: "", lat: 21.1702, lng: 72.8311,
    classification: "PORT CITY",
    image: WIKI("Surat_Castle_2.jpg"),
    known_for: "Ancient port at the mouth of the Tapti, today a global diamond-cutting and textile hub, historically the premier emporium of the Mughal western coast.",
    colonial_history: "Surat hosted the East India Company's very first factory in India, established in 1612 after the naval Battle of Swally against the Portuguese secured trading rights from the Mughals. For decades it was the Company's principal western base and the chief Mughal port for the Haj. Its commercial primacy faded after the rise of Bombay, to which the Company shifted its headquarters in 1687."
  },
  {
    name: "Pune", alias: "Poona", lat: 18.5204, lng: 73.8567,
    classification: "GARRISON TOWN",
    image: WIKI("Shaniwarwada_gate.jpg"),
    known_for: "The Maratha capital and 'Oxford of the East', a centre of learning, the Shaniwar Wada palace, and a cool-weather retreat from Bombay.",
    colonial_history: "Pune was the seat of the Peshwas, who led the Maratha Confederacy until their defeat. The British victory at Khadki and the fall of the last Peshwa Baji Rao II in 1818 ended Maratha power and brought the Deccan under Company rule. The British built a large cantonment, and Poona became the monsoon capital of the Bombay Presidency. It was also a hotbed of nationalism — home to reformers and the radical leader Bal Gangadhar Tilak."
  },
  {
    name: "Agra", alias: "", lat: 27.1767, lng: 78.0081,
    classification: "GARRISON TOWN",
    image: WIKI("Taj_Mahal_in_March_2004.jpg"),
    known_for: "City of the Taj Mahal, Agra Fort, and Fatehpur Sikri nearby — the supreme showcase of Mughal architecture and a former imperial capital.",
    colonial_history: "Agra came under British control in 1803 after the Second Anglo-Maratha War. It served briefly as the capital of the North-Western Provinces and saw fighting during the 1857 Rebellion, when Europeans took refuge in Agra Fort. Under British custody the Taj Mahal was repaired and its gardens reshaped — Lord Curzon notably championed its restoration around 1900, lamenting earlier neglect and vandalism."
  },
  {
    name: "Varanasi", alias: "Benares", lat: 25.3176, lng: 82.9739,
    classification: "TRADING POST",
    image: WIKI("Dasaswamedh_Ghat_on_the_Ganges,_Varanasi.jpg"),
    known_for: "One of the world's oldest continually inhabited cities, the holiest in Hinduism, famed for its riverside ghats, silk weaving, and Sanskrit scholarship.",
    colonial_history: "Benares was a wealthy commercial and religious centre incorporated into Company territory in 1775. In 1781 Warren Hastings' attempt to extort funds from Raja Chait Singh provoked a violent uprising that nearly cost Hastings his life. The British later recognised a titular Maharaja of Benares while administering the region, and founded institutions that fed into the city's enduring tradition of learning."
  },
  {
    name: "Nagpur", alias: "", lat: 21.1458, lng: 79.0882,
    classification: "PRINCELY STATE",
    image: WIKI("Nagpur_Vidhan_Bhavan.jpg"),
    known_for: "The 'Orange City' at the geographic centre of India, known as the zero-mile marker and a major orange-growing and administrative hub.",
    colonial_history: "Nagpur was the capital of the Bhonsle Marathas. After the last raja died without a natural heir in 1853, Lord Dalhousie annexed the kingdom under the controversial 'Doctrine of Lapse', refusing to recognise an adopted successor — a grievance that fed into the discontent of 1857. The British made Nagpur the capital of the Central Provinces, developing it as a cotton and railway centre."
  },
  {
    name: "Mysore", alias: "Mysuru", lat: 12.2958, lng: 76.6394,
    classification: "PRINCELY STATE",
    image: WIKI("Mysore_Palace_Morning.jpg"),
    known_for: "City of palaces, sandalwood, silk, and the dazzling Dasara festival, seat of the Wadiyar dynasty and a model of enlightened princely governance.",
    colonial_history: "Mysore was the power base of Hyder Ali and Tipu Sultan, the British East India Company's most formidable Indian adversaries across four Anglo-Mysore Wars. Tipu's death at the storming of Seringapatam in 1799 ended the threat; the British restored the Wadiyar dynasty as a subsidiary princely state under a Resident. The state became renowned for progressive administration, education, and early industrialisation."
  },
  {
    name: "Trivandrum", alias: "Thiruvananthapuram", lat: 8.5241, lng: 76.9366,
    classification: "PRINCELY STATE",
    image: WIKI("Kanakakunnu_Palace.jpg"),
    known_for: "Capital of Travancore, a green coastal city of temples and palaces, home to the fabulously wealthy Padmanabhaswamy Temple.",
    colonial_history: "Trivandrum was the capital of the princely state of Travancore, which entered a subsidiary alliance with the British in 1795. Travancore was celebrated as a 'model state' for its early investments in education, public health, and infrastructure under its maharajas and able dewans. It retained internal autonomy under a British Resident until its accession to India after 1947."
  },
  {
    name: "Cochin", alias: "Kochi", lat: 9.9312, lng: 76.2673,
    classification: "PORT CITY",
    image: WIKI("Chinese_fishing_nets_Kochi.jpg"),
    known_for: "Historic spice port on the Malabar Coast, layered with Portuguese, Dutch, Jewish, and British heritage, famed for its Chinese fishing nets and backwaters.",
    colonial_history: "Cochin was the first European colonial settlement in India — the Portuguese built a fort here in 1503, followed by Dutch conquest in 1663 and finally British dominance from 1795. The pepper and spice trade made it perennially coveted. Under the British it formed part of the princely state of Cochin and remained a vital port, with the modern harbour developed in the early twentieth century by engineer Robert Bristow."
  },
  {
    name: "Vizag", alias: "Visakhapatnam", lat: 17.6868, lng: 83.2185,
    classification: "PORT CITY",
    image: WIKI("Visakhapatnam_Beach_Road.jpg"),
    known_for: "A natural deep-water harbour on the Bay of Bengal ringed by the Eastern Ghats, today a major port and naval base.",
    colonial_history: "Visakhapatnam was a coastal town of the Northern Circars, ceded to the British in the late eighteenth century and administered within the Madras Presidency. Its sheltered bay made it a useful trading and shipping point. The British developed port facilities, and the modern harbour was inaugurated in 1933, laying the foundation for the city's later emergence as a shipbuilding and naval centre."
  },
  {
    name: "Peshawar", alias: "", lat: 34.0151, lng: 71.5249,
    classification: "GARRISON TOWN",
    image: WIKI("Islamia_College_Peshawar.jpg"),
    known_for: "Ancient frontier city at the mouth of the Khyber Pass, the storied gateway between the subcontinent and Central Asia, rich in Gandharan history.",
    colonial_history: "Peshawar was annexed by the British in 1849 after the conquest of the Sikh Empire and became the key garrison guarding the volatile North-West Frontier and the Khyber Pass against Afghan and tribal incursions. It was a forward base in the 'Great Game' rivalry with Russia and a launching point for the Anglo-Afghan Wars. The frontier here saw constant punitive expeditions throughout the Raj."
  }
];

/* ---------- TIER 2 — SECONDARY COLONIAL TOWNS ---------- */
const TIER2 = [
  { name:"Simla", alias:"Shimla", lat:31.1048, lng:77.1734, classification:"HILL STATION", image:WIKI("Christ_Church,_Shimla.jpg"),
    known_for:"Queen of Hill Stations, Himalayan resort of mock-Tudor villas, the Ridge, and a toy railway winding up from the plains.",
    colonial_history:"Developed from the 1820s, Simla became the summer capital of British India from 1864, to which the entire imperial government decamped each hot season. From this Himalayan perch the Viceroy ruled a fifth of humanity; the Viceregal Lodge and Gaiety Theatre embodied Raj society at leisure." },
  { name:"Jaipur", alias:"", lat:26.9124, lng:75.7873, classification:"PRINCELY STATE", image:WIKI("Hawa_Mahal_2011.jpg"),
    known_for:"The 'Pink City', planned in 1727 with the Hawa Mahal, City Palace, and Jantar Mantar observatory; a jewel of Rajput architecture.",
    colonial_history:"Capital of the princely state of Jaipur, which signed a subsidiary treaty with the British in 1818. Its maharajas were prominent loyalist allies; the city was famously painted pink in 1876 to welcome the Prince of Wales." },
  { name:"Jodhpur", alias:"", lat:26.2389, lng:73.0243, classification:"PRINCELY STATE", image:WIKI("Mehrangarh_Fort,_Jodhpur.jpg"),
    known_for:"The 'Blue City' of the Thar's edge, crowned by the mighty Mehrangarh Fort and the Umaid Bhawan Palace.",
    colonial_history:"Capital of the Marwar princely state, allied to the British by treaty in 1818. Its rulers and the Jodhpur Lancers served the Raj loyally, notably in cavalry charges during the First World War." },
  { name:"Udaipur", alias:"", lat:24.5854, lng:73.7125, classification:"PRINCELY STATE", image:WIKI("Lake_Palace_Udaipur.jpg"),
    known_for:"The 'City of Lakes', romantic Rajput capital of Mewar with the Lake Palace and City Palace mirrored in Lake Pichola.",
    colonial_history:"Capital of Mewar, whose Sisodia rulers proudly claimed the highest Rajput precedence. Mewar accepted British protection in 1818 while jealously guarding its prestige as the house that had most resisted Mughal domination." },
  { name:"Indore", alias:"", lat:22.7196, lng:75.8577, classification:"PRINCELY STATE", image:WIKI("Rajwada_Indore.jpg"),
    known_for:"Commercial hub of central India and capital of the Holkar dynasty, known for the Rajwada palace and Lal Bagh.",
    colonial_history:"Capital of the Holkar Maratha state, brought under British subsidiary alliance after the Treaty of Mandsaur in 1818. Indore became the headquarters of the British Central India Agency and a cotton and trading centre." },
  { name:"Bhopal", alias:"", lat:23.2599, lng:77.4126, classification:"PRINCELY STATE", image:WIKI("Taj-ul-Masajid_Bhopal.jpg"),
    known_for:"City of lakes and mosques, notably ruled by a succession of women — the Begums of Bhopal — and site of the vast Taj-ul-Masajid.",
    colonial_history:"A Muslim princely state allied with the British from 1818, Bhopal was unusual for its line of capable female rulers, the Begums, who modernised the state while remaining staunch imperial allies." },
  { name:"Gwalior", alias:"", lat:26.2183, lng:78.1828, classification:"PRINCELY STATE", image:WIKI("Gwalior_Fort.jpg"),
    known_for:"Dominated by its colossal hilltop fort and the Jai Vilas Palace, seat of the Scindia dynasty and a centre of Hindustani music.",
    colonial_history:"Capital of the Scindia Marathas. Its fortress changed hands repeatedly; the British stormed it in 1858 during the final phase of the Rebellion, where Rani Lakshmibai of Jhansi was killed in battle nearby." },
  { name:"Baroda", alias:"Vadodara", lat:22.3072, lng:73.1812, classification:"PRINCELY STATE", image:WIKI("Laxmi_Vilas_Palace,_Vadodara.jpg"),
    known_for:"Cultured capital of the Gaekwads, home to the opulent Laxmi Vilas Palace and a tradition of arts patronage and education.",
    colonial_history:"Capital of the Gaekwad princely state. Under the reformist Maharaja Sayajirao Gaekwad III, Baroda pioneered free primary education, libraries, and banking, becoming a model progressive state under nominal British paramountcy." },
  { name:"Ahmedabad", alias:"", lat:23.0225, lng:72.5714, classification:"TRADING POST", image:WIKI("Sidi_Saiyyed_Jaali.jpg"),
    known_for:"Great textile city of Gujarat, the 'Manchester of India', with exquisite stepwells, mosques, and the Sabarmati Ashram.",
    colonial_history:"A major Mughal-era textile centre that became a British district capital and a booming cotton-mill town. It was the base from which Mahatma Gandhi led the independence movement, founding the Sabarmati Ashram in 1917 and launching the 1930 Salt March from here." },
  { name:"Srinagar", alias:"", lat:34.0837, lng:74.7973, classification:"PRINCELY STATE", image:WIKI("Dal_Lake,_Srinagar.jpg"),
    known_for:"Summer capital of Kashmir, city of the Dal Lake, houseboats, Mughal gardens, and the Jhelum's wooden bridges.",
    colonial_history:"Capital of the princely state of Jammu and Kashmir, created in 1846 when the British sold the Vale to the Dogra ruler Gulab Singh under the Treaty of Amritsar. A British Resident oversaw the strategically vital Himalayan state." },
  { name:"Quetta", alias:"", lat:30.1798, lng:66.9750, classification:"GARRISON TOWN", image:WIKI("Quetta_City.jpg"),
    known_for:"High mountain-ringed city of Balochistan, gateway to the Bolan Pass and Afghanistan, surrounded by orchards.",
    colonial_history:"Occupied by the British in 1876 under Robert Sandeman, Quetta became a crucial frontier garrison and home to the Staff College guarding the approaches to Afghanistan. A catastrophic earthquake destroyed the city in 1935." },
  { name:"Multan", alias:"", lat:30.1575, lng:71.5249, classification:"TRADING POST", image:WIKI("Shrine_of_Bahauddin_Zakariya,_Multan.jpg"),
    known_for:"Ancient 'City of Saints' in southern Punjab, famed for Sufi shrines, blue pottery, and searing summers.",
    colonial_history:"The 1848 murder of two British officers at Multan sparked the Second Anglo-Sikh War; the British besieged and stormed the fort in 1849, precipitating the annexation of the entire Punjab." },
  { name:"Rawalpindi", alias:"", lat:33.5651, lng:73.0169, classification:"GARRISON TOWN", image:WIKI("Rawalpindi_Cantt.jpg"),
    known_for:"Twin city of Islamabad, a major commercial and military centre on the Grand Trunk Road below the Murree hills.",
    colonial_history:"The final battle of the Second Anglo-Sikh War was fought near here in 1849. The British made Rawalpindi the largest military cantonment and army headquarters in northern India, a status it retained as a key garrison." },
  { name:"Sialkot", alias:"", lat:32.4927, lng:74.5319, classification:"TRADING POST", image:WIKI("Sialkot_Clock_Tower.jpg"),
    known_for:"Industrial Punjabi city renowned worldwide for manufacturing sports goods, surgical instruments, and leather.",
    colonial_history:"A British district and cantonment town in Punjab. Its garrison rose in revolt during the 1857 Rebellion. Under the Raj it developed the export industries — footballs, gut, and instruments — for which it remains globally known." },
  { name:"Chittagong", alias:"Chattogram", lat:22.3569, lng:91.7832, classification:"PORT CITY", image:WIKI("Chittagong_Port_aerial.jpg"),
    known_for:"Bangladesh's principal seaport, a green hilly harbour city opening onto the Bay of Bengal.",
    colonial_history:"Ceded to the East India Company by the Nawab of Bengal in 1760, Chittagong became a key British port. It is famous for the 1930 Chittagong Armoury Raid led by Surya Sen, a daring revolutionary assault on British arsenals." },
  { name:"Sylhet", alias:"", lat:24.8949, lng:91.8687, classification:"TRADING POST", image:WIKI("Shahjalal_Dargah_Sylhet.jpg"),
    known_for:"Tea-garden region of north-eastern Bengal, lush and hilly, a centre of Sufi pilgrimage to the shrine of Shah Jalal.",
    colonial_history:"Annexed by the Company in 1765, Sylhet became a centre of British tea cultivation. Administered as part of Assam, it was the subject of a 1947 referendum that placed it in East Pakistan rather than India." },
  { name:"Mandalay", alias:"", lat:21.9588, lng:96.0891, classification:"PROVINCIAL CAPITAL", image:WIKI("Mandalay_Palace.jpg"),
    known_for:"The last royal capital of Burma beneath Mandalay Hill, a centre of Buddhist learning and Burmese culture.",
    colonial_history:"The royal capital of King Thibaw, captured by the British in the Third Anglo-Burmese War of 1885. Thibaw was exiled to India and the Burmese monarchy abolished as Upper Burma was annexed into British India." },
  { name:"Meerut", alias:"", lat:28.9845, lng:77.7064, classification:"GARRISON TOWN", image:WIKI("St._John's_Church,_Meerut.jpg"),
    known_for:"Industrial city north-east of Delhi, a major military cantonment and centre of sports-goods manufacture.",
    colonial_history:"Meerut is where the Rebellion of 1857 ignited: on 10 May, sepoys enraged by the greased-cartridge controversy mutinied, freed comrades, and marched on Delhi — the spark of the first great challenge to British rule." },
  { name:"Bareilly", alias:"", lat:28.3670, lng:79.4304, classification:"GARRISON TOWN", image:WIKI("Bareilly_City.jpg"),
    known_for:"A Rohilkhand city known for furniture, zari embroidery, and as a centre of Islamic scholarship.",
    colonial_history:"Capital of the Rohillas before British conquest, Bareilly became a major centre of the 1857 uprising under Khan Bahadur Khan, who briefly established rebel rule before British forces retook the city in 1858." },
  { name:"Moradabad", alias:"", lat:28.8386, lng:78.7733, classification:"TRADING POST", image:WIKI("Jama_Masjid_Moradabad.jpg"),
    known_for:"The 'Brass City' (Peetal Nagri), world-famous for engraved brassware and metal handicrafts.",
    colonial_history:"A district town of the United Provinces that participated in the 1857 Rebellion. Under the British its brass-ware export industry flourished, supplying ornamental metalwork across the empire." },
  { name:"Gorakhpur", alias:"", lat:26.7606, lng:83.3732, classification:"GARRISON TOWN", image:WIKI("Gorakhnath_Temple_Gorakhpur.jpg"),
    known_for:"Centre of the Nath yogi tradition and the Gorakhnath Temple, a railway junction near the Nepal border.",
    colonial_history:"A British district headquarters and recruiting ground. Nearby Chauri Chaura saw the 1922 incident when a mob burned a police station, prompting Gandhi to suspend the Non-Cooperation Movement over the violence." },
  { name:"Jabalpur", alias:"", lat:23.1815, lng:79.9864, classification:"GARRISON TOWN", image:WIKI("Marble_Rocks_Bhedaghat.jpg"),
    known_for:"Central Indian city by the marble rocks of the Narmada at Bhedaghat, a major cantonment and railway town.",
    colonial_history:"Headquarters of the British campaign against the Thuggee cults under William Sleeman in the 1830s. Jabalpur became a key cantonment and administrative centre of the Central Provinces." },
  { name:"Raipur", alias:"", lat:21.2514, lng:81.6296, classification:"TRADING POST", image:WIKI("Raipur_railway_station.jpg"),
    known_for:"Capital of Chhattisgarh, a steel and rice-trading centre in the eastern Deccan plains.",
    colonial_history:"Part of the Maratha-ruled Chhattisgarh region absorbed into the British Central Provinces. Raipur developed as a district town and railway-linked agricultural market under colonial administration." },
  { name:"Cuttack", alias:"", lat:20.4625, lng:85.8830, classification:"PROVINCIAL CAPITAL", image:WIKI("Barabati_Fort_Cuttack.jpg"),
    known_for:"The historic 'Millennium City' of Odisha on the Mahanadi delta, famed for silver filigree work.",
    colonial_history:"Captured from the Marathas in 1803, Cuttack became the administrative capital of British Orissa. It bore the brunt of the catastrophic 1866 Orissa Famine, which killed roughly a third of the region's population amid official inaction." },
  { name:"Bhubaneswar", alias:"", lat:20.2961, lng:85.8245, classification:"TRADING POST", image:WIKI("Lingaraj_Temple_Bhubaneswar_11007.jpg"),
    known_for:"The 'Temple City' of Odisha with hundreds of sandstone shrines, notably the Lingaraj Temple; now a planned state capital.",
    colonial_history:"An ancient temple town near Cuttack under British Orissa. Its modern incarnation as a planned capital was designed by Otto Königsberger only after independence, but its temples drew colonial-era archaeological attention." },
  { name:"Vijayawada", alias:"", lat:16.5062, lng:80.6480, classification:"TRADING POST", image:WIKI("Kanaka_Durga_Temple_Vijayawada.jpg"),
    known_for:"Bustling commercial city on the Krishna river, a major trade and transport hub of the Andhra region.",
    colonial_history:"Within the Madras Presidency, Vijayawada's fortunes were transformed by the British construction of the Krishna Barrage (the Prakasam Barrage's predecessor) in the 1850s, which irrigated the delta and made it a rich agricultural market." },
  { name:"Coimbatore", alias:"", lat:11.0168, lng:76.9558, classification:"TRADING POST", image:WIKI("Coimbatore_Railway_Station.jpg"),
    known_for:"The 'Manchester of South India', a cotton-textile and engineering city in the shadow of the Western Ghats.",
    colonial_history:"Ceded to the British after the fall of Tipu Sultan in 1799, Coimbatore grew within the Madras Presidency into a major textile-manufacturing centre, powered later by hydroelectricity from the Pykara falls." },
  { name:"Madurai", alias:"", lat:9.9252, lng:78.1198, classification:"TRADING POST", image:WIKI("Meenakshi_Amman_temple_Tower.jpg"),
    known_for:"Ancient temple city built around the soaring Meenakshi Amman Temple, a 2,500-year-old centre of Tamil culture and learning.",
    colonial_history:"A former Nayak and Carnatic capital that came under Company control in the late eighteenth century. The British made it a district headquarters of the Madras Presidency; the American Mission established colleges that shaped the city." },
  { name:"Tiruchirappalli", alias:"Trichy", lat:10.7905, lng:78.7047, classification:"GARRISON TOWN", image:WIKI("Rockfort_Trichy.jpg"),
    known_for:"City of the Rock Fort temple and the vast Srirangam island shrine on the Kaveri, a centre of learning and engineering.",
    colonial_history:"Trichinopoly was a key prize in the Anglo-French Carnatic Wars of the 1750s, where Robert Clive and Stringer Lawrence campaigned. The British siege and relief here helped establish Company supremacy over the French in the south." },
  { name:"Salem", alias:"", lat:11.6643, lng:78.1460, classification:"TRADING POST", image:WIKI("Salem_City_View.jpg"),
    known_for:"Steel and textile city ringed by hills in western Tamil Nadu, known for mangoes and sago.",
    colonial_history:"Acquired by the British after the Mysore wars, Salem became a district of the Madras Presidency. It was an early centre of administrative experiment, including Thomas Munro's influential ryotwari land-revenue system." },
  { name:"Mangalore", alias:"Mangaluru", lat:12.9141, lng:74.8560, classification:"PORT CITY", image:WIKI("Mangalore_port.jpg"),
    known_for:"Coastal port of Karnataka where the Netravati meets the Arabian Sea, famed for its tiles, cuisine, and trade.",
    colonial_history:"Contested in the Anglo-Mysore Wars, Mangalore gave its name to the 1784 Treaty of Mangalore between Tipu Sultan and the Company. The British later made it a Madras Presidency port; its red-clay roof tiles roofed buildings across the empire." },
  { name:"Hubli", alias:"Hubballi", lat:15.3647, lng:75.1240, classification:"TRADING POST", image:WIKI("Hubli_Railway_Station.jpg"),
    known_for:"Commercial heart of north Karnataka and a major cotton and railway centre, twinned with Dharwad.",
    colonial_history:"Hubli grew under British rule as a key cotton-trading town and the headquarters of the Southern Mahratta Railway, making it a vital junction linking the Deccan to the western ports." },
  { name:"Belgaum", alias:"Belagavi", lat:15.8497, lng:74.4977, classification:"GARRISON TOWN", image:WIKI("Belgaum_Fort.jpg"),
    known_for:"Hill-bordered city on the Maharashtra–Karnataka frontier, a military cantonment with an old fort.",
    colonial_history:"Taken from the Marathas in 1818, Belgaum became a major British cantonment guarding the Deccan. The Indian National Congress held its 1924 session here — the only one ever presided over by Mahatma Gandhi." },
  { name:"Sholapur", alias:"Solapur", lat:17.6599, lng:75.9064, classification:"TRADING POST", image:WIKI("Solapur_Bhuikot_Fort.jpg"),
    known_for:"Textile city of the Maharashtra Deccan, famed for its chaddars (terry towels) and bedsheets.",
    colonial_history:"A British cotton-mill town that became a stronghold of labour and nationalist agitation. In 1930 Sholapur briefly fell under the control of protesters who established a parallel government, met with martial law and executions." },
  { name:"Aurangabad", alias:"Chhatrapati Sambhajinagar", lat:19.8762, lng:75.3433, classification:"GARRISON TOWN", image:WIKI("Bibi_Ka_Maqbara_Aurangabad.jpg"),
    known_for:"Gateway to the Ajanta and Ellora caves, city of the Bibi Ka Maqbara, a former Mughal Deccan capital.",
    colonial_history:"Named for the emperor Aurangzeb, who made it his Deccan base, the city later fell within the Nizam of Hyderabad's princely dominion, with a British-influenced administration and a notable cantonment." },
  { name:"Nasik", alias:"Nashik", lat:19.9975, lng:73.7898, classification:"TRADING POST", image:WIKI("Trimbakeshwar_Temple.jpg"),
    known_for:"Sacred city on the Godavari, a Kumbh Mela site, wine country, and home to the India Security Press.",
    colonial_history:"A Bombay Presidency district town and pilgrimage centre. Nasik was the scene of the 1909 assassination of district magistrate A.M.T. Jackson by the revolutionary Anant Kanhere, a landmark in the armed nationalist struggle." },
  { name:"Kolhapur", alias:"", lat:16.7050, lng:74.2433, classification:"PRINCELY STATE", image:WIKI("New_Palace_Kolhapur.jpg"),
    known_for:"Maratha princely capital known for its Mahalakshmi temple, wrestling tradition, leather chappals, and spicy cuisine.",
    colonial_history:"A princely state ruled by descendants of Shivaji, allied with the British from 1812. Its reformist ruler Shahu Maharaj pioneered affirmative action, reserving posts for lower castes decades before independence." },
  { name:"Goa", alias:"Panaji", lat:15.4909, lng:73.8278, classification:"PORT CITY", image:WIKI("Basilica_of_Bom_Jesus_Goa.jpg"),
    known_for:"Portuguese-flavoured coastal territory of beaches, baroque churches, and the relics of St. Francis Xavier at Old Goa.",
    colonial_history:"Unlike British India, Goa was the jewel of the Portuguese Estado da Índia from 1510, the seat of the Viceroy and the Inquisition. It remained Portuguese throughout the British Raj and was only annexed by India in 1961." },
  { name:"Calicut", alias:"Kozhikode", lat:11.2588, lng:75.7804, classification:"PORT CITY", image:WIKI("Kozhikode_Beach.jpg"),
    known_for:"Spice port of the Malabar Coast where Vasco da Gama landed in 1498, giving the world the word 'calico'.",
    colonial_history:"The Zamorin's port that opened Europe's sea route to India. After contests between Portuguese, Dutch, and Mysore's rulers, the British took the Malabar in 1792, governing it from Madras and exporting its pepper and timber." },
  { name:"Pondicherry", alias:"Puducherry", lat:11.9416, lng:79.8083, classification:"TRADING POST", image:WIKI("Pondicherry_promenade.jpg"),
    known_for:"Former French enclave of seaside boulevards, mustard-yellow villas, and the Sri Aurobindo Ashram.",
    colonial_history:"The capital of French India from 1674, Pondicherry was the great rival of British Madras during the Carnatic Wars under Governor Dupleix. Captured and restored several times, it remained French until ceded to India in 1954." },
  { name:"Vellore", alias:"", lat:12.9165, lng:79.1325, classification:"GARRISON TOWN", image:WIKI("Vellore_Fort.jpg"),
    known_for:"Fort city of northern Tamil Nadu, today renowned for the Christian Medical College hospital.",
    colonial_history:"Vellore Fort was the site of the 1806 Vellore Mutiny — the first major sepoy uprising against the Company, sparked by new dress regulations — a bloody precursor to 1857. Tipu Sultan's family was held captive in the fort." },
  { name:"Thanjavur", alias:"Tanjore", lat:10.7870, lng:79.1378, classification:"PRINCELY STATE", image:WIKI("Thanjavur_Brihadeeswarar_Temple.jpg"),
    known_for:"Capital of the Chola heartland, home to the towering Brihadeeswarar Temple and the celebrated Tanjore painting style.",
    colonial_history:"The Maratha-ruled kingdom of Tanjore came under British influence; its last ruler, Serfoji II, was a cultured patron of arts and science under Company tutelage. The fertile Kaveri delta made it a prized revenue district." }
];

/* ---------- TIER 3 — TOWNS & VILLAGES ----------
   Compact format: [name, lat, lng, classification, known_for]
   Colonial blurb is generated for these. */
const T3_CLS = {
  R:"REGIONAL TOWN", D:"DISTRICT SEAT", P:"PILGRIMAGE TOWN",
  H:"HILL STATION", I:"INDUSTRIAL TOWN", T:"TRADING POST", G:"GARRISON TOWN"
};
const TIER3_RAW = [
  ["Muzaffarpur",26.1209,85.3647,"T","Litchi-growing town of north Bihar on the Burhi Gandak."],
  ["Darbhanga",26.1542,85.8918,"D","Seat of the Darbhanga Raj, a great Maithil zamindari estate."],
  ["Bhagalpur",25.2445,86.9718,"T","Silk city ('Silk City of India') on the Ganga, famed for tussar."],
  ["Gaya",24.7955,85.0002,"P","Hindu pilgrimage town and gateway to Bodh Gaya's Mahabodhi Temple."],
  ["Munger",25.3764,86.4737,"I","Ganga-side town known historically for arms manufacture."],
  ["Bettiah",26.8023,84.5028,"D","Champaran town linked to Gandhi's first satyagraha of 1917."],
  ["Chapra",25.7811,84.7470,"T","Saran district town and old saltpetre-trading centre."],
  ["Saran",25.9167,84.7500,"D","Agrarian district of the Saran plains in Bihar."],
  ["Sitamarhi",26.5946,85.4901,"P","Pilgrimage town held to be the birthplace of Sita."],
  ["Deoghar",24.4823,86.6938,"P","Jharkhand temple town of the Baidyanath jyotirlinga."],
  ["Ranchi",23.3441,85.3096,"H","Plateau city, summer capital of Bihar, hill resort of Chota Nagpur."],
  ["Hazaribagh",23.9925,85.3637,"H","Cool plateau town and former British sanatorium station."],
  ["Jamshedpur",22.8046,86.2029,"I","India's first planned steel city, founded by the Tatas."],
  ["Dhanbad",23.7957,86.4304,"I","The 'Coal Capital of India' on the Jharia coalfield."],
  ["Bokaro",23.6693,86.1511,"I","Steel-plant city of the Damodar valley."],
  ["Rourkela",22.2604,84.8536,"I","Steel town of western Odisha in the Brahmani valley."],
  ["Sambalpur",21.4669,83.9756,"T","Textile town on the Mahanadi, famed for ikat sambalpuri sarees."],
  ["Berhampur",19.3150,84.7941,"T","Silk-trading 'Silk City' of southern Odisha."],
  ["Balasore",21.4934,86.9335,"T","Coastal Odisha town and old European trading factory site."],
  ["Puri",19.8135,85.8312,"P","Great pilgrimage town of the Jagannath Temple and Rath Yatra."],
  ["Kharagpur",22.3460,87.2320,"I","Railway town with one of the world's longest platforms."],
  ["Midnapore",22.4257,87.3199,"D","West Bengal district town, a centre of revolutionary nationalism."],
  ["Burdwan",23.2324,87.8615,"D","Bardhaman, seat of a great Bengali zamindari and rice market."],
  ["Krishnanagar",23.4009,88.5023,"T","Nadia town famed for clay-modelling artisans."],
  ["Murshidabad",24.1833,88.2667,"R","Former Nawabi capital of Bengal before Plassey."],
  ["Malda",25.0119,88.1433,"T","Mango and silk town of north Bengal near ancient Gaur."],
  ["Siliguri",26.7271,88.3953,"T","Gateway to the Darjeeling hills and the north-east."],
  ["Jalpaiguri",26.5435,88.7195,"D","Dooars tea-region town of north Bengal."],
  ["Cooch Behar",26.3242,89.4514,"R","Planned princely-state capital with a grand Rajbari palace."],
  ["Dibrugarh",27.4728,94.9120,"T","Upper Assam tea city, the 'Tea City of India'."],
  ["Jorhat",26.7509,94.2037,"T","Assam tea town, former Ahom capital region."],
  ["Tezpur",26.6338,92.8000,"G","Historic Assam town on the Brahmaputra, near the NEFA frontier."],
  ["Guwahati",26.1445,91.7362,"R","Gateway of the north-east and the Kamakhya temple city."],
  ["Shillong",25.5788,91.8933,"H","'Scotland of the East', British hill capital of Assam."],
  ["Imphal",24.8170,93.9368,"G","Manipur valley capital, site of the pivotal 1944 WWII battle."],
  ["Agartala",23.8315,91.2868,"R","Tripura princely capital with the Ujjayanta Palace."],
  ["Aizawl",23.7271,92.7176,"H","Hill capital of the Mizo (Lushai) highlands."],
  ["Kohima",25.6701,94.1077,"G","Naga hill town, site of the decisive 1944 Battle of Kohima."],
  ["Itanagar",27.0844,93.6053,"H","Eastern Himalayan town of the Arunachal frontier."],
  ["Bikaner",28.0229,73.3119,"R","Thar desert princely capital with Junagarh Fort and camel corps."],
  ["Ajmer",26.4499,74.6399,"D","Sufi pilgrimage city of the Dargah of Moinuddin Chishti."],
  ["Pushkar",26.4897,74.5511,"P","Sacred lake town with India's only major Brahma temple."],
  ["Kota",25.2138,75.8648,"I","Chambal-river industrial and education town of Rajasthan."],
  ["Bharatpur",27.2152,77.5030,"R","Jat princely-state fort city near the Keoladeo bird sanctuary."],
  ["Alwar",27.5530,76.6346,"R","Rajput princely capital between Delhi and Jaipur."],
  ["Sikar",27.6094,75.1399,"T","Shekhawati town of painted havelis and merchant wealth."],
  ["Pali",25.7711,73.3234,"T","Marwar textile and trading town south of Jodhpur."],
  ["Barmer",25.7521,71.3962,"R","Far-western desert town near the Sind frontier."],
  ["Jaisalmer",26.9157,70.9083,"T","'Golden City' fort on the Thar caravan routes."],
  ["Hissar",29.1492,75.7217,"G","Haryana garrison and cattle-breeding town founded by Firoz Shah."],
  ["Rohtak",28.8955,76.6066,"D","Haryana district town on the Delhi approaches."],
  ["Ambala",30.3782,76.7767,"G","Major British cantonment and railway junction of east Punjab."],
  ["Ludhiana",30.9010,75.8573,"I","Punjab's largest city, hosiery and bicycle manufacturing hub."],
  ["Jalandhar",31.3260,75.5762,"I","Doaba city famed for sports-goods and the Lyallpur khalsa."],
  ["Ferozepur",30.9259,74.6133,"G","Frontier cantonment and arsenal on the old Sutlej border."],
  ["Pathankot",32.2643,75.6421,"G","Strategic junction town at the foot of the Kangra hills."],
  ["Gurdaspur",32.0410,75.4053,"D","Majha district town near the Ravi and the Partition line."],
  ["Hoshiarpur",31.5143,75.9115,"D","Doaba district town below the Shivalik foothills."],
  ["Patiala",30.3398,76.3869,"R","Sikh princely-state capital, home of the Patiala turban and pegs."],
  ["Bathinda",30.2110,74.9455,"G","Malwa fort town and old Punjab garrison."],
  ["Dharamsala",32.2190,76.3234,"H","Kangra-valley hill station, later seat of the Tibetan exile."],
  ["Kullu",31.9576,77.1095,"H","Himachal valley town of the Dussehra festival."],
  ["Mandi",31.7080,76.9318,"H","Beas-river temple town, 'Varanasi of the hills'."],
  ["Solan",30.9045,77.0967,"H","Himachal hill town, the 'Mushroom City', near Shimla."],
  ["Nahan",30.5598,77.2945,"H","Sirmaur princely-state hill capital."],
  ["Dehra Dun",30.3165,78.0322,"H","Doon-valley garrison town, home of the military academy and survey."],
  ["Haridwar",29.9457,78.1642,"P","Ganga pilgrimage gateway and Kumbh Mela city."],
  ["Rishikesh",30.0869,78.2676,"P","Himalayan-foothills 'Yoga Capital' on the Ganga."],
  ["Nainital",29.3919,79.4542,"H","Kumaon lake hill station, summer capital of the United Provinces."],
  ["Almora",29.5892,79.6467,"H","Kumaon hill town with sweeping Himalayan views."],
  ["Pithoragarh",29.5829,80.2181,"H","'Little Kashmir' near the Nepal–Tibet frontier."],
  ["Muzaffarnagar",29.4727,77.7085,"T","Sugarcane and jaggery market town of the Doab."],
  ["Saharanpur",29.9680,77.5552,"I","Wood-carving town at the head of the Doab."],
  ["Aligarh",27.8974,78.0880,"I","Lock-making city, home of Aligarh Muslim University."],
  ["Mathura",27.4924,77.6737,"P","Krishna's birthplace, a major Hindu pilgrimage centre."],
  ["Etawah",26.7855,79.0150,"D","Yamuna-ravine district town of the central Doab."],
  ["Banda",25.4760,80.3360,"D","Bundelkhand district town, a centre of the 1857 revolt."],
  ["Jhansi",25.4484,78.5685,"G","Fort city of Rani Lakshmibai, heroine of the 1857 Rebellion."],
  ["Sagar",23.8388,78.7378,"G","Lake-side Bundelkhand cantonment of the Central Provinces."],
  ["Damoh",23.8330,79.4420,"D","Bundelkhand district town of the Central Provinces."],
  ["Satna",24.6005,80.8322,"I","Limestone and cement town of the Vindhya region."],
  ["Rewa",24.5362,81.3037,"R","Princely capital of Baghelkhand, land of the white tiger."],
  ["Ujjain",23.1765,75.7885,"P","Ancient Shipra-river city of the Mahakaleshwar jyotirlinga."],
  ["Mandsaur",24.0768,75.0683,"T","Malwa town of the 1818 treaty subduing the Pindaris."],
  ["Khandwa",21.8257,76.3525,"I","Nimar railway-junction town of central India."],
  ["Burhanpur",21.3145,76.2300,"R","Tapti-river Mughal city, gateway to the Deccan."],
  ["Betul",21.9010,77.9010,"D","Satpura-plateau district town of the Central Provinces."],
  ["Chhindwara",22.0574,78.9382,"D","Satpura highland district town and orange-growing belt."],
  ["Seoni",22.0869,79.5439,"R","Highland town that inspired Kipling's 'Jungle Book' setting."],
  ["Balaghat",21.8123,80.1853,"I","Manganese-mining district town of the eastern Satpuras."],
  ["Durg",21.1904,81.2849,"I","Twin of Bhilai, a steel and trading town of Chhattisgarh."],
  ["Bilaspur",22.0797,82.1409,"I","Railway and rice town of central Chhattisgarh."],
  ["Jagdalpur",19.0748,82.0322,"R","Bastar princely-state capital amid tribal highlands."],
  ["Ambikapur",23.1255,83.1989,"R","Surguja princely-state town of northern Chhattisgarh."],
  ["Korba",22.3595,82.7501,"I","Coal and power town of the Hasdeo valley."],
  ["Rajnandgaon",21.0972,81.0379,"R","Princely-state town west of Raipur, a cotton-mill centre."],
  ["Akola",20.7002,77.0082,"T","Cotton-trading town of the Berar Deccan."],
  ["Amravati",20.9374,77.7796,"T","Berar cotton city, an old trade and temple centre."],
  ["Yavatmal",20.3888,78.1204,"T","Cotton-belt district town of Vidarbha."],
  ["Nanded",19.1383,77.3210,"P","Godavari-river city of Sikhism's Hazur Sahib gurudwara."],
  ["Latur",18.4088,76.5604,"T","Marathwada trading town of the former Hyderabad state."],
  ["Osmanabad",18.1860,76.0419,"D","Marathwada district town named for the last Nizam."],
  ["Bidar",17.9133,77.5301,"R","Deccan fort city famed for bidri metal inlay craft."],
  ["Gulbarga",17.3297,76.8343,"R","Kalaburagi, former Bahmani Sultanate capital of the Deccan."],
  ["Bijapur",16.8302,75.7100,"R","Vijayapura, Adil Shahi city of the great Gol Gumbaz dome."],
  ["Dharwad",15.4589,75.0078,"D","Twin of Hubli, an education and Hindustani-music centre."],
  ["Davangere",14.4644,75.9218,"I","Cotton-mill 'Manchester of Karnataka' in the Deccan."],
  ["Shimoga",13.9299,75.5681,"T","Shivamogga, gateway to the Malnad and the Western Ghats."],
  ["Tumkur",13.3379,77.1173,"T","Coconut and trade town north-west of Bangalore."],
  ["Kolar",13.1367,78.1296,"I","Gold-fields town, site of the historic Kolar gold mines."],
  ["Hassan",13.0072,76.0962,"D","Gateway town to the Hoysala temples of Belur and Halebidu."],
  ["Chitradurga",14.2251,76.4000,"G","Boulder-strewn fort town of seven-walled ramparts."],
  ["Raichur",16.2120,77.3439,"R","Doab fort town between the Krishna and Tungabhadra."],
  ["Bellary",15.1394,76.9214,"G","Iron-ore and fort town, a Madras Presidency garrison."],
  ["Hospet",15.2693,76.3871,"R","Town beside the ruins of Vijayanagara at Hampi."],
  ["Udupi",13.3409,74.7421,"P","Coastal temple town of the Krishna Matha and its cuisine."],
  ["Chikmagalur",13.3161,75.7720,"H","Coffee-plantation hill town of the Baba Budan range."],
  ["Kodagu",12.4218,75.7400,"H","Coorg, the misty coffee-and-warrior highland of Karnataka."],
  ["Mandya",12.5223,76.8954,"T","Sugarcane town of the Kaveri-irrigated Mysore plains."],
  ["Chamrajnagar",11.9261,76.9437,"D","Southernmost Karnataka district town near the Nilgiris."],
  ["Erode",11.3410,77.7172,"T","Turmeric and textile market town of the Kongu region."],
  ["Tirupur",11.1085,77.3411,"I","Knitwear 'Banian City', a global cotton-garment hub."],
  ["Dindigul",10.3673,77.9803,"T","Fort and lock-making town below the Sirumalai hills."],
  ["Virudhunagar",9.5810,77.9624,"T","Trading 'Sandhanai City' of the Nadar merchant community."],
  ["Tirunelveli",8.7139,77.7567,"D","Tamraparni-river town, a southern Madras district seat."],
  ["Nagercoil",8.1833,77.4119,"T","Kanyakumari-district town near India's southern tip."],
  ["Ramanathapuram",9.3639,78.8395,"R","Setupati seat near the Rameswaram pilgrimage causeway."],
  ["Sivaganga",9.8433,78.4809,"R","Chettinad-region town of the Maruthu Pandiyar rebels."],
  ["Pudukkottai",10.3833,78.8001,"R","Last princely state of the Tamil south, the Tondaiman seat."],
  ["Karur",10.9601,78.0766,"I","Amaravathi-river textile and bus-body building town."],
  ["Namakkal",11.2189,78.1674,"T","Fort and poultry town of the Kongu uplands."],
  ["Dharmapuri",12.1357,78.1580,"D","Hill-and-mango district town of north-western Tamil Nadu."],
  ["Krishnagiri",12.5186,78.2137,"T","Mango and granite town on the Bangalore–Chennai axis."],
  ["Cuddalore",11.7480,79.7714,"T","Coastal town beside old Fort St. David, a Company stronghold."],
  ["Nagapattinam",10.7672,79.8420,"T","Coromandel port, an old Dutch and Company trading harbour."],
  ["Mayiladuthurai",11.1018,79.6552,"P","Kaveri-delta temple town of the Mayuranathar shrine."],
  ["Ariyalur",11.1401,79.0782,"I","Limestone and cement town of the central Kaveri belt."],
  ["Perambalur",11.2342,78.8807,"D","Agrarian district town of central Tamil Nadu."],
  ["Villupuram",11.9401,79.4861,"R","Railway-junction town of the northern Tamil country."],
  ["Kallakurichi",11.7382,78.9596,"D","Sugar and agrarian district town of the Kalvarayan hills."],
  ["Tiruvannamalai",12.2253,79.0747,"P","Temple town of the Arunachaleswarar shrine and sacred hill."],
  ["Ranipet",12.9344,79.3334,"I","Leather-tanning town founded by the British near Arcot."],
  ["Tirupathur",12.4951,78.5670,"T","Foothill trade town between the Eastern Ghats and Karnataka."],
  ["Kancheepuram",12.8342,79.7036,"P","'City of a Thousand Temples' and the famed Kanchi silk sarees."],
  ["Chengalpattu",12.6919,79.9760,"G","Fort and railway town south of Madras, a Company district seat."],
  ["Tambaram",12.9249,80.1000,"G","Southern Madras garrison suburb, a WWII airbase site."],
  ["Pallavaram",12.9675,80.1491,"R","Ancient cantonment suburb on the Madras–Chengalpattu road."],
  ["Tiruvallur",13.1429,79.9094,"P","Temple town of the Veeraraghava shrine near Madras."],
  ["Guntakal",15.1674,77.3666,"I","Major railway-junction town of Rayalaseema."],
  ["Kurnool",15.8281,78.0373,"R","Tungabhadra town, briefly capital of Andhra State."],
  ["Nellore",14.4426,79.9865,"T","Penna-delta rice and aquaculture town on the Coromandel."],
  ["Chittoor",13.2172,79.1003,"T","Mango and trade town of southern Rayalaseema."],
  ["Kadapa",14.4673,78.8242,"R","Cuddapah, a Rayalaseema fort and trade town."],
  ["Anantapur",14.6819,77.6006,"D","Dry Rayalaseema district seat of the Deccan plateau."],
  ["Hindupur",13.8283,77.4911,"T","Silk and trading town on the Karnataka border."],
  ["Rajahmundry",17.0005,81.8040,"R","Godavari-bank city, cradle of the Telugu literary renaissance."],
  ["Eluru",16.7107,81.0952,"T","Wool-carpet and trading town of the Godavari delta."],
  ["Machilipatnam",16.1875,81.1389,"T","Masulipatnam, a great early Company port for painted calicoes."],
  ["Guntur",16.3067,80.4365,"T","Tobacco and chilli market city of the Krishna delta."],
  ["Ongole",15.5057,80.0499,"T","Coastal trade town famed for its Ongole cattle breed."],
  ["Nalgonda",17.0575,79.2684,"D","Telangana district town of the former Hyderabad state."],
  ["Warangal",17.9689,79.5941,"R","Kakatiya dynasty capital, fort and famed Thousand-Pillar temple."],
  ["Khammam",17.2473,80.1514,"D","Fort and coal-belt district town of eastern Telangana."],
  ["Karimnagar",18.4386,79.1288,"T","Granite and filigree-craft town of northern Telangana."],
  ["Nizamabad",18.6725,78.0941,"T","Turmeric and trade town of the former Nizam's dominion."],
  ["Adilabad",19.6641,78.5320,"R","Forested northern Telangana district town near Maharashtra."],
  ["Mahbubnagar",16.7375,77.9866,"D","Palamuru district town of southern Telangana."],
  ["Medak",18.0461,78.2604,"P","Cathedral town with one of Asia's largest churches."],
  ["Sangareddy",17.6294,78.0820,"D","District town west of Hyderabad on the Deccan plateau."]
];

/* ---------- TIER 3 (EXTENDED) — wider subcontinent & British India sphere ---------- */
const TIER3_RAW2 = [
  /* PAKISTAN */
  ["Faisalabad",31.4180,73.0790,"I","Lyallpur, Punjab's great canal-colony textile city."],
  ["Gujranwala",32.1877,74.1945,"I","Wrestlers' city of central Punjab."],
  ["Sargodha",32.0836,72.6711,"G","Punjab garrison and citrus belt town."],
  ["Sahiwal",30.6660,73.1000,"T","Montgomery, a canal-colony cotton town."],
  ["Bahawalpur",29.3956,71.6836,"R","Former Nawabi princely capital near the Cholistan."],
  ["Sukkur",27.7052,68.8574,"T","Indus-barrage trade town of upper Sindh."],
  ["Larkana",27.5589,68.2120,"D","Sindh town near ancient Mohenjo-daro."],
  ["Hyderabad Sindh",25.3960,68.3578,"R","Talpur capital on the Indus, distinct from the Deccan city."],
  ["Mirpur Khas",25.5276,69.0116,"T","Sindh mango and rail-junction town."],
  ["Nawabshah",26.2442,68.4096,"D","Central Sindh agricultural district town."],
  ["Jhang",31.2681,72.3181,"R","Chenab-side town of Punjabi folklore."],
  ["Dera Ghazi Khan",30.0489,70.6403,"R","Indus frontier town of the Derajat."],
  ["Abbottabad",34.1688,73.2215,"H","Hazara hill cantonment founded by James Abbott."],
  ["Mardan",34.1989,72.0231,"G","Town near the Gandharan ruins of Takht-i-Bahi."],
  ["Kohat",33.5869,71.4414,"G","Frontier garrison south of Peshawar."],
  ["Bannu",32.9889,70.6056,"G","Waziristan-frontier garrison town."],
  ["Dera Ismail Khan",31.8313,70.9019,"G","Indus frontier town of the Derajat."],
  ["Mingora",34.7795,72.3614,"R","Chief town of the Swat valley."],
  ["Gilgit",35.9221,74.3087,"H","High-mountain town of the Karakoram frontier."],
  ["Skardu",35.2971,75.6333,"H","Baltistan town below the Karakoram peaks."],
  ["Muzaffarabad",34.3700,73.4711,"R","Capital of Pakistan-administered Kashmir."],
  ["Chitral",35.8511,71.7889,"H","Hindu Kush frontier princely town."],
  ["Gwadar",25.1264,62.3225,"T","Makran deep-sea port, once an Omani enclave."],
  ["Sibi",29.5430,67.8773,"G","Furnace-hot Balochistan rail and garrison town."],
  ["Jacobabad",28.2769,68.4514,"G","Sindh frontier town named for John Jacob."],
  ["Kasur",31.1187,74.4500,"T","Punjab town of the poet Bulleh Shah."],
  ["Jhelum",32.9333,73.7333,"G","Grand Trunk Road garrison on the Jhelum river."],
  ["Wah",33.7740,72.7610,"I","Cantonment and ordnance town near Taxila."],
  ["Mansehra",34.3333,73.2000,"R","Hazara town near the Ashokan rock edicts."],
  ["Nowshera",34.0153,71.9747,"G","Frontier cantonment on the Kabul river."],
  ["Taxila",33.7463,72.7872,"P","Ancient Gandharan seat of learning near Rawalpindi."],
  ["Chakwal",32.9300,72.8550,"D","Potohar-plateau district town."],
  /* BANGLADESH */
  ["Rajshahi",24.3636,88.6241,"T","Silk and mango city on the Padma."],
  ["Khulna",22.8456,89.5403,"I","South-western city, gateway to the Sundarbans."],
  ["Barisal",22.7010,90.3535,"R","Riverine 'Venice of Bengal' of the south."],
  ["Rangpur",25.7439,89.2752,"D","Northern Bengal tobacco and agri town."],
  ["Comilla",23.4607,91.1809,"D","Eastern Bengal town near the Tripura border."],
  ["Mymensingh",24.7471,90.4203,"D","Brahmaputra-side education town."],
  ["Jessore",23.1664,89.2081,"T","Western Bengal town near the India border."],
  ["Bogra",24.8466,89.3776,"R","Town near ancient Mahasthangarh, oldest in Bengal."],
  ["Dinajpur",25.6217,88.6354,"R","North-Bengal rice and zamindari town."],
  ["Pabna",24.0064,89.2372,"T","Padma-side weaving and dairy town."],
  ["Tangail",24.2513,89.9167,"T","Sari-weaving town north of Dhaka."],
  ["Narayanganj",23.6238,90.4990,"I","Jute river-port, the 'Dundee of Bengal'."],
  ["Cox's Bazar",21.4272,92.0058,"R","World's longest natural sea beach."],
  ["Noakhali",22.8696,91.0995,"D","Coastal district of Gandhi's 1946 peace march."],
  ["Kushtia",23.9013,89.1206,"P","Town of the mystic bard Lalon Shah."],
  ["Faridpur",23.6070,89.8429,"D","Padma-delta district town."],
  ["Jamalpur",24.9375,89.9372,"D","Brahmaputra-side northern town."],
  ["Saidpur",25.7783,88.8924,"I","Old railway-workshop town of the north."],
  /* SRI LANKA (CEYLON) */
  ["Colombo",6.9271,79.8612,"T","Ceylon's chief colonial port and commercial capital."],
  ["Kandy",7.2906,80.6337,"P","Last Sinhalese royal capital, Temple of the Tooth."],
  ["Galle",6.0535,80.2210,"T","Dutch-fort port of the southern coast."],
  ["Jaffna",9.6615,80.0255,"R","Tamil cultural capital of northern Ceylon."],
  ["Trincomalee",8.5874,81.2152,"G","Great natural harbour and eastern naval base."],
  ["Anuradhapura",8.3114,80.4037,"P","Ancient Sinhalese capital of stupas and tanks."],
  ["Nuwara Eliya",6.9497,80.7891,"H","'Little England' tea hill station of Ceylon."],
  ["Batticaloa",7.7170,81.7000,"T","Lagoon town of the eastern coast."],
  ["Negombo",7.2083,79.8358,"T","Catholic fishing-and-canal town near Colombo."],
  ["Badulla",6.9934,81.0550,"H","Uva-province tea-country hill town."],
  /* NEPAL */
  ["Kathmandu",27.7172,85.3240,"R","Himalayan capital of temples and durbar squares."],
  ["Pokhara",28.2096,83.9856,"H","Lakeside town beneath the Annapurnas."],
  ["Biratnagar",26.4525,87.2718,"I","Eastern Tarai industrial border town."],
  ["Birgunj",27.0000,84.8667,"T","Tarai trade gateway to India."],
  ["Janakpur",26.7288,85.9266,"P","Mithila pilgrimage town, birthplace of Sita."],
  ["Bhaktapur",27.6710,85.4298,"P","Newar temple city of the Kathmandu valley."],
  ["Nepalgunj",28.0500,81.6167,"T","Mid-western Tarai trade town."],
  ["Dharan",26.8120,87.2830,"G","Hill-foot former Gurkha recruiting town."],
  /* BHUTAN */
  ["Thimphu",27.4728,89.6390,"R","Himalayan capital of the dragon kingdom."],
  ["Paro",27.4333,89.4167,"P","Valley town of the cliffside Tiger's Nest."],
  ["Phuntsholing",26.8600,89.3900,"T","Border trade town with Indian Bengal."],
  /* MYANMAR (BURMA) */
  ["Bago",17.3350,96.4815,"R","Pegu, former Mon kingdom capital."],
  ["Pathein",16.7790,94.7320,"T","Bassein, delta rice port of the Irrawaddy."],
  ["Mawlamyine",16.4905,97.6283,"T","Moulmein, first capital of British Burma."],
  ["Sittwe",20.1469,92.8688,"T","Akyab, Arakan-coast port."],
  ["Taunggyi",20.7891,97.0378,"H","Shan-plateau hill town."],
  ["Pyay",18.8249,95.2253,"R","Prome, ancient Pyu city on the Irrawaddy."],
  ["Monywa",22.1083,95.1358,"T","Trade town on the Chindwin river."],
  ["Meiktila",20.8776,95.8585,"G","Central-Burma garrison and WWII battle town."],
  ["Myitkyina",25.3833,97.3956,"G","Kachin railhead of the far north."],
  ["Lashio",22.9333,97.7500,"T","Northern Shan town on the old Burma Road."],
  ["Magway",20.1500,94.9500,"T","Dry-zone Irrawaddy oil town."],
  ["Toungoo",18.9434,96.4360,"R","Former Taungoo-dynasty royal capital."],
  ["Dawei",14.0828,98.1919,"T","Tavoy, a Tenasserim-coast port."],
  /* AFGHANISTAN (ANGLO-AFGHAN FRONTIER) */
  ["Kabul",34.5553,69.2075,"G","Afghan capital, focus of three Anglo-Afghan wars."],
  ["Kandahar",31.6133,65.7100,"G","Southern Afghan city of the 1880 battle."],
  ["Jalalabad",34.4265,70.4515,"G","Khyber-route town of the 1842 retreat from Kabul."],
  /* UTTAR PRADESH */
  ["Ayodhya",26.7990,82.2040,"P","Sacred Ramayana city on the Sarayu."],
  ["Faizabad",26.7750,82.1450,"G","Old Awadh capital and cantonment near Ayodhya."],
  ["Raebareli",26.2310,81.2330,"D","Awadh district town, a Nehru-Gandhi seat."],
  ["Sultanpur",26.2600,82.0730,"D","Gomti-side Awadh district town."],
  ["Azamgarh",26.0685,83.1836,"D","Eastern UP town of poets and weavers."],
  ["Ghazipur",25.5800,83.5770,"I","Ganga town of the colonial opium factory."],
  ["Jaunpur",25.7480,82.6840,"R","Sharqi-sultanate city of mosques."],
  ["Mirzapur",25.1460,82.5690,"T","Carpet-weaving town on the Ganga."],
  ["Basti",26.7920,82.7340,"D","Eastern UP district town."],
  ["Gonda",27.1330,81.9610,"D","Awadh terai district town."],
  ["Bahraich",27.5740,81.5940,"P","Terai town of the Bahraich dargah."],
  ["Sitapur",27.5670,80.6820,"D","Awadh district town north of Lucknow."],
  ["Hardoi",27.3950,80.1310,"D","Central Awadh district town."],
  ["Unnao",26.5470,80.4880,"D","Doab town between Lucknow and Kanpur."],
  ["Fatehpur",25.9300,80.8130,"D","Doab district town of the 1857 revolt."],
  ["Firozabad",27.1591,78.3958,"I","Glass-bangle manufacturing city."],
  ["Mainpuri",27.2300,79.0270,"D","Doab district town."],
  ["Farrukhabad",27.3929,79.5800,"T","Ganga town of old calico printing."],
  ["Kannauj",27.0550,79.9180,"T","Ancient capital, India's attar (perfume) city."],
  ["Shahjahanpur",27.8800,79.9100,"G","Rohilkhand cantonment town."],
  ["Pilibhit",28.6310,79.8050,"D","Terai town near the Sharda forests."],
  ["Rampur",28.7900,79.0260,"R","Former Nawabi state of the Raza Library."],
  ["Bijnor",29.3720,78.1360,"D","Upper-Doab district town."],
  ["Bulandshahr",28.4070,77.8530,"D","Doab district town east of Delhi."],
  ["Hathras",27.5970,78.0530,"I","Trading and asafoetida town."],
  ["Ballia",25.7580,84.1490,"D","Easternmost UP town, the 'Baghi Ballia' of 1942."],
  ["Ghaziabad",28.6692,77.4538,"I","Industrial gateway city east of Delhi."],
  /* BIHAR */
  ["Begusarai",25.4182,86.1272,"I","Industrial Ganga town, 'Leningrad of Bihar'."],
  ["Hajipur",25.6850,85.2090,"T","Confluence trade town opposite Patna."],
  ["Sasaram",24.9533,84.0300,"R","Town of Sher Shah Suri's grand tomb."],
  ["Bihar Sharif",25.2000,85.5240,"P","Sufi-shrine town near ancient Nalanda."],
  ["Siwan",26.2200,84.3560,"D","Saran-region district town."],
  ["Madhubani",26.3486,86.0716,"P","Mithila town famed for its folk paintings."],
  ["Purnia",25.7771,87.4753,"D","Eastern Bihar agricultural district town."],
  ["Katihar",25.5390,87.5710,"I","Eastern Bihar rail-junction town."],
  ["Nawada",24.8870,85.5430,"D","Magadh-region district town."],
  ["Samastipur",25.8560,85.7800,"D","North-Bihar rail-junction district town."],
  /* JHARKHAND */
  ["Giridih",24.1913,86.3000,"I","Coal and mica town of the Chota Nagpur."],
  ["Daltonganj",24.0333,84.0670,"D","Palamu district town (Medininagar)."],
  ["Chaibasa",22.5530,85.8020,"R","Singhbhum tribal-region town."],
  ["Dumka",24.2676,87.2497,"R","Santhal Parganas headquarters."],
  ["Sahibganj",25.2500,87.6460,"T","Ganga river-port town of the east."],
  /* WEST BENGAL */
  ["Asansol",23.6839,86.9523,"I","Coal-and-steel city of the Damodar valley."],
  ["Durgapur",23.5204,87.3119,"I","Planned steel city of the Damodar."],
  ["Darjeeling",27.0410,88.2663,"H","Himalayan tea hill station and toy railway."],
  ["Kalimpong",27.0590,88.4690,"H","Eastern Himalayan trade-route hill town."],
  ["Kurseong",26.8800,88.2770,"H","Misty tea hill town below Darjeeling."],
  ["Bankura",23.2324,87.0717,"T","Terracotta-temple and Baluchari-saree town."],
  ["Purulia",23.3320,86.3650,"R","Westernmost Bengal plateau town."],
  ["Bishnupur",23.0760,87.3190,"P","Malla-kingdom town of terracotta temples."],
  ["Haldia",22.0667,88.0698,"I","Petrochemical river-port of the Hooghly mouth."],
  ["Barrackpore",22.7600,88.3700,"G","Cantonment where Mangal Pandey revolted in 1857."],
  ["Raiganj",25.6190,88.1240,"D","North-Bengal district town."],
  /* ODISHA */
  ["Jharsuguda",21.8554,84.0062,"I","Western Odisha coal and power town."],
  ["Angul",20.8400,85.1010,"I","Coal and aluminium town of central Odisha."],
  ["Keonjhar",21.6290,85.5810,"I","Iron-ore mining district town."],
  ["Baripada",21.9347,86.7335,"R","Mayurbhanj former princely-state town."],
  ["Bhawanipatna",19.9070,83.1670,"R","Kalahandi district town of western Odisha."],
  ["Koraput",18.8120,82.7110,"H","Eastern-Ghats tribal highland town."],
  /* ASSAM & NORTH-EAST */
  ["Silchar",24.8333,92.7789,"T","Barak-valley town of southern Assam."],
  ["Nagaon",26.3500,92.6900,"D","Central Assam district town."],
  ["Tinsukia",27.4920,95.3470,"I","Upper-Assam oil and tea junction town."],
  ["Sivasagar",26.9850,94.6380,"R","Former Ahom-dynasty capital of Assam."],
  ["Gangtok",27.3389,88.6065,"H","Himalayan capital of Sikkim."],
  ["Tawang",27.5860,91.8590,"P","High Buddhist-monastery town of Arunachal."],
  ["Dimapur",25.9091,93.7270,"T","Nagaland's commercial gateway town."],
  /* RAJASTHAN */
  ["Chittorgarh",24.8790,74.6290,"R","Mewar fort city of legendary Rajput sieges."],
  ["Bhilwara",25.3470,74.6360,"I","Textile 'Manchester of Rajasthan'."],
  ["Sri Ganganagar",29.9094,73.8800,"T","Canal-colony agri town near the Punjab border."],
  ["Sawai Madhopur",26.0220,76.3440,"R","Town beside Ranthambore fort and tiger reserve."],
  ["Banswara",23.5410,74.4350,"R","'City of a hundred islands' in the south."],
  ["Dungarpur",23.8430,73.7140,"R","Southern Rajput hill-state town."],
  ["Nagaur",27.2020,73.7390,"R","Thar fort and cattle-fair town."],
  ["Hanumangarh",29.5810,74.3290,"T","Ghaggar-side town near Kalibangan."],
  /* GUJARAT */
  ["Rajkot",22.3039,70.8022,"R","Saurashtra city where Gandhi went to school."],
  ["Bhavnagar",21.7645,72.1519,"T","Saurashtra port and former princely capital."],
  ["Jamnagar",22.4707,70.0577,"R","Brass-city and former Nawanagar capital."],
  ["Junagadh",21.5222,70.4579,"R","Girnar-foot town of the contested 1947 accession."],
  ["Porbandar",21.6417,69.6293,"P","Coastal town, birthplace of Mahatma Gandhi."],
  ["Bhuj",23.2420,69.6669,"R","Kutch desert former princely capital."],
  ["Bharuch",21.7051,72.9959,"T","Ancient Broach, a Narmada-mouth trading port."],
  ["Anand",22.5645,72.9289,"I","Town of the Amul dairy cooperative."],
  ["Mehsana",23.5880,72.3690,"T","North-Gujarat dairy and oil town."],
  ["Gandhinagar",23.2156,72.6369,"R","Planned modern capital of Gujarat."],
  ["Veraval",20.9077,70.3670,"T","Fishing port beside the Somnath temple."],
  /* MADHYA PRADESH */
  ["Ratlam",23.3315,75.0367,"T","Malwa rail-junction and sev-snack town."],
  ["Dewas",22.9676,76.0534,"I","Malwa industrial and former twin-princely town."],
  ["Khargone",21.8235,75.6100,"T","Nimar cotton-belt town."],
  ["Vidisha",23.5251,77.8081,"P","Ancient Besnagar near the Sanchi stupas."],
  ["Chhatarpur",24.9170,79.5880,"P","Bundelkhand town near the Khajuraho temples."],
  ["Katni",23.8340,80.3940,"I","Limestone and rail-junction town."],
  ["Shahdol",23.2960,81.3560,"I","Eastern-MP coal and tribal-region town."],
  ["Mandla",22.5980,80.3710,"R","Gondwana-kingdom town on the Narmada."],
  /* MAHARASHTRA */
  ["Thane",19.2183,72.9781,"I","City of India's first railway terminus."],
  ["Satara",17.6805,73.9933,"R","Maratha princely town beneath Ajinkyatara fort."],
  ["Sangli",16.8524,74.5815,"T","Turmeric-trade town of southern Maharashtra."],
  ["Ahmednagar",19.0948,74.7480,"G","Nizam Shahi fort town and 1942 detention site."],
  ["Jalgaon",21.0077,75.5626,"T","Khandesh banana-belt trade town."],
  ["Dhule",20.9042,74.7749,"T","Khandesh cotton and trade town."],
  ["Chandrapur",19.9615,79.2961,"I","Vidarbha coal and ferro-alloy town."],
  ["Ratnagiri",16.9902,73.3120,"T","Konkan port, Tilak's birthplace and Thibaw's exile."],
  ["Wardha",20.7453,78.6022,"R","Town of Gandhi's Sevagram ashram."],
  /* TELANGANA & ANDHRA */
  ["Tirupati",13.6288,79.4192,"P","Pilgrim city of the hilltop Venkateswara temple."],
  ["Vizianagaram",18.1067,83.3956,"R","Northern-AP former princely-state town."],
  ["Srikakulam",18.2949,83.8938,"D","Northern-coastal Andhra district town."],
  ["Tenali",16.2430,80.6400,"T","Krishna-delta 'Paris of Andhra' trade town."],
  ["Nandyal",15.4780,78.4830,"T","Rayalaseema trade and cement town."],
  ["Adoni",15.6270,77.2740,"T","Rayalaseema cotton-market town."],
  ["Kothagudem",17.5500,80.6190,"I","Singareni coalfield town of Telangana."],
  ["Siddipet",18.1010,78.8520,"D","Telangana district town north of Hyderabad."],
  /* KARNATAKA */
  ["Bagalkot",16.1810,75.6960,"R","Malaprabha-side trade town of north Karnataka."],
  ["Gadag",15.4290,75.6300,"T","Cotton and temple town of the Deccan."],
  ["Karwar",14.8138,74.1290,"T","Konkan-coast port of north Karnataka."],
  ["Sirsi",14.6200,74.8360,"P","Malnad areca-nut and temple town."],
  ["Chikballapur",13.4355,77.7315,"T","Trade town north of Bangalore."],
  ["Ramanagara",12.7217,77.2800,"I","Silk-cocoon market town near Bangalore."],
  /* TAMIL NADU & KERALA */
  ["Hosur",12.7409,77.8253,"I","Industrial town on the Karnataka border."],
  ["Pollachi",10.6580,77.0090,"T","Coconut and market town near the Anamalais."],
  ["Palani",10.4500,77.5210,"P","Hill-temple town of Lord Murugan."],
  ["Chidambaram",11.3994,79.6936,"P","Town of the cosmic-dance Nataraja temple."],
  ["Thrissur",10.5276,76.2144,"P","Cultural capital of Kerala, the Pooram-festival city."],
  ["Palakkad",10.7867,76.6548,"G","Gap-town fort guarding the route into Kerala."],
  ["Kollam",8.8932,76.6141,"T","Quilon, an ancient Malabar spice and cashew port."],
  ["Alappuzha",9.4981,76.3388,"T","Alleppey, the 'Venice of the East' backwater town."],
  ["Kottayam",9.5916,76.5222,"T","Rubber-trade and literacy town of Kerala."],
  ["Kannur",11.8745,75.3704,"G","Cannanore, an old Arakkal and British garrison port."],
  ["Thalassery",11.7480,75.4929,"T","Tellicherry, an early British factory and cricket town."],
  ["Munnar",10.0889,77.0595,"H","High-range tea plantation hill station."],
  ["Kalpetta",11.6090,76.0830,"H","Wayanad highland plantation town."],
  /* PUNJAB, HARYANA, HIMACHAL & UTTARAKHAND */
  ["Karnal",29.6857,76.9905,"T","Haryana grain-bowl and dairy town."],
  ["Panipat",29.3909,76.9635,"G","Town of three empire-deciding battles."],
  ["Sonipat",28.9931,77.0151,"I","Haryana industrial town north of Delhi."],
  ["Kurukshetra",29.9695,76.8783,"P","Mahabharata battlefield pilgrimage town."],
  ["Rewari",28.1990,76.6190,"I","Brass and railway-heritage town of south Haryana."],
  ["Gurgaon",28.4595,77.0266,"I","Boom-city satellite south-west of Delhi."],
  ["Faridabad",28.4089,77.3178,"I","Industrial city south of Delhi."],
  ["Yamunanagar",30.1290,77.2674,"I","Timber and plywood industrial town."],
  ["Moga",30.8160,75.1710,"T","Malwa-Punjab grain-trade town."],
  ["Kapurthala",31.3800,75.3800,"R","Former princely town of Indo-French architecture."],
  ["Ropar",30.9670,76.5270,"P","Sutlej town near a Harappan site."],
  ["Roorkee",29.8543,77.8880,"I","Engineering-college and Ganga-canal town."],
  ["Mussoorie",30.4598,78.0644,"H","'Queen of the Hills' above Dehra Dun."],
  ["Chamba",32.5560,76.1260,"R","Ravi-valley former princely hill town."],
  ["Una",31.4685,76.2708,"D","Himachal foothill town bordering Punjab."],
  ["Kashipur",29.2104,78.9619,"I","Terai industrial town of Kumaon."]
];

/* Build full Tier 3 records with generated colonial blurb */
const REGION_NOTE = "Under British rule it was administered as a subordinate town within its presidency, province, or a protected princely state, its trade, revenue, and order overseen from a distant district headquarters of the Raj.";
const TIER3 = TIER3_RAW.concat(TIER3_RAW2).map(([name,lat,lng,clsKey,known]) => ({
  name, alias:"", lat, lng, tier:3,
  classification: T3_CLS[clsKey],
  image: WIKI("India_relief_location_map.jpg"),
  known_for: known,
  colonial_history: `${name} lay within the wider sphere of British India. ${REGION_NOTE}`
}));

/* Attach tier numbers and merge */
TIER1.forEach(c => c.tier = 1);
TIER2.forEach(c => c.tier = 2);
const CITIES = [...TIER1, ...TIER2, ...TIER3];
